sylius_grid:
    grids:
        setono_sylius_feed_admin_violation:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_feed.model.violation.class%"
                    repository:
                        method: createQueryBuilderByFeed
                        arguments:
                            feed: $id
            limits: [200, 100, 500, 1000]
            fields:
                channel:
                    type: string
                    label: setono_sylius_feed.ui.channel
                locale:
                    type: string
                    label: setono_sylius_feed.ui.locale
                severity:
                    type: string
                    label: setono_sylius_feed.ui.severity
                message:
                    type: string
                    label: setono_sylius_feed.ui.message
                data:
                    type: twig
                    label: setono_sylius_feed.ui.data
                    options:
                        template: "@SetonoSyliusFeedPlugin/Admin/Violation/Grid/Field/data.html.twig"
            filters:
                channel:
                    type: entity
                    label: setono_sylius_feed.ui.channel
                    form_options:
                        class: "%sylius.model.channel.class%"
                locale:
                    type: entity
                    label: setono_sylius_feed.ui.locale
                    form_options:
                        class: "%sylius.model.locale.class%"
                severity:
                    type: string
                    label: setono_sylius_feed.ui.severity
                data:
                    type: string
                    label: setono_sylius_feed.ui.data
